import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { OntologicalModelingLanguageGeneratedModule, OntologicalModelingLanguageGeneratedSharedModule } from './generated/module.js';
import { OntologicalModelingLanguageValidator, registerValidationChecks } from './ontological-modeling-language-validator.js';
import { OMLScopeComputation, OMLScopeProvider } from './ontological-modeling-language-scope.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type OntologicalModelingLanguageAddedServices = {
    validation: {
        OntologicalModelingLanguageValidator: OntologicalModelingLanguageValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type OntologicalModelingLanguageServices = LangiumServices & OntologicalModelingLanguageAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const OntologicalModelingLanguageModule: Module<OntologicalModelingLanguageServices, PartialLangiumServices & OntologicalModelingLanguageAddedServices> = {
    validation: {
        OntologicalModelingLanguageValidator: () => new OntologicalModelingLanguageValidator()
    },
    references: {
        ScopeComputation: (services) => new OMLScopeComputation(services),
        ScopeProvider: (services) => new OMLScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createOntologicalModelingLanguageServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    OntologicalModelingLanguage: OntologicalModelingLanguageServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        OntologicalModelingLanguageGeneratedSharedModule
    );
    const OntologicalModelingLanguage = inject(
        createDefaultModule({ shared }),
        OntologicalModelingLanguageGeneratedModule,
        OntologicalModelingLanguageModule
    );
    shared.ServiceRegistry.register(OntologicalModelingLanguage);
    registerValidationChecks(OntologicalModelingLanguage);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, OntologicalModelingLanguage };
}
